version: '3.7'
services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/psycho_telegram_bot
      - ./psycho_telegram_bot/staticfiles:/psycho_telegram_bot/staticfiles
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - psycho_network

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=psycho_user
      - POSTGRES_PASSWORD=psycho_password
      - POSTGRES_DB=psycho_dev
    networks:
      - psycho_network

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - backend
    volumes:
      - ./psycho_telegram_bot/staticfiles:/psycho_telegram_bot/staticfiles
    networks:
      - psycho_network

  telegram_bot:
    build: .
    command: python app/telegram_bot.py
    depends_on:
      - backend
    networks:
      - psycho_network

  cron:
    build: 
      context: .
      dockerfile: Dockerfile.cron
    command: sh -c "crond -f -d 8 >> /var/log/cron.log 2>&1"
    volumes:
      - ./shedule.sh:/psycho_telegram_bot/shedule.sh
      - cron_logs:/var/log
    networks:
      - psycho_network

volumes:
  postgres_data:
  cron_logs:

networks:
  psycho_network:
